//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.16 at 09:33:26 PM CET 
//


package pl.konczak.nzoz.ewus.client.old.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="status_cwu"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="-1"/&gt;
 *               &lt;enumeration value="0"/&gt;
 *               &lt;enumeration value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="numer_pesel" type="{https://ewus.nfz.gov.pl/ws/broker/ewus/status_cwu/v3}pesel"/&gt;
 *         &lt;element name="system_nfz" type="{https://ewus.nfz.gov.pl/ws/broker/ewus/status_cwu/v3}system"/&gt;
 *         &lt;element name="swiad" type="{https://ewus.nfz.gov.pl/ws/broker/ewus/status_cwu/v3}swiadczeniodawca"/&gt;
 *         &lt;element name="pacjent" type="{https://ewus.nfz.gov.pl/ws/broker/ewus/status_cwu/v3}swiadczeniobiorca" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id_operacji" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;minLength value="8"/&gt;
 *             &lt;maxLength value="20"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="data_czas_operacji" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "statusCwu",
    "numerPesel",
    "systemNfz",
    "swiad",
    "pacjent",
    "signature"
})
@XmlRootElement(name = "status_cwu_odp", namespace = "https://ewus.nfz.gov.pl/ws/broker/ewus/status_cwu/v3")
public class StatusCwuOdp {

    @XmlElement(name = "status_cwu", namespace = "https://ewus.nfz.gov.pl/ws/broker/ewus/status_cwu/v3", required = true)
    protected String statusCwu;
    @XmlElement(name = "numer_pesel", namespace = "https://ewus.nfz.gov.pl/ws/broker/ewus/status_cwu/v3", required = true)
    protected String numerPesel;
    @XmlElement(name = "system_nfz", namespace = "https://ewus.nfz.gov.pl/ws/broker/ewus/status_cwu/v3", required = true)
    protected System systemNfz;
    @XmlElement(namespace = "https://ewus.nfz.gov.pl/ws/broker/ewus/status_cwu/v3", required = true)
    protected Swiadczeniodawca swiad;
    @XmlElement(namespace = "https://ewus.nfz.gov.pl/ws/broker/ewus/status_cwu/v3")
    protected Swiadczeniobiorca pacjent;
    @XmlElement(name = "Signature")
    protected SignatureType signature;
    @XmlAttribute(name = "id_operacji", required = true)
    protected String idOperacji;
    @XmlAttribute(name = "data_czas_operacji", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataCzasOperacji;

    /**
     * Gets the value of the statusCwu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusCwu() {
        return statusCwu;
    }

    /**
     * Sets the value of the statusCwu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusCwu(String value) {
        this.statusCwu = value;
    }

    /**
     * Gets the value of the numerPesel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumerPesel() {
        return numerPesel;
    }

    /**
     * Sets the value of the numerPesel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumerPesel(String value) {
        this.numerPesel = value;
    }

    /**
     * Gets the value of the systemNfz property.
     * 
     * @return
     *     possible object is
     *     {@link System }
     *     
     */
    public System getSystemNfz() {
        return systemNfz;
    }

    /**
     * Sets the value of the systemNfz property.
     * 
     * @param value
     *     allowed object is
     *     {@link System }
     *     
     */
    public void setSystemNfz(System value) {
        this.systemNfz = value;
    }

    /**
     * Gets the value of the swiad property.
     * 
     * @return
     *     possible object is
     *     {@link Swiadczeniodawca }
     *     
     */
    public Swiadczeniodawca getSwiad() {
        return swiad;
    }

    /**
     * Sets the value of the swiad property.
     * 
     * @param value
     *     allowed object is
     *     {@link Swiadczeniodawca }
     *     
     */
    public void setSwiad(Swiadczeniodawca value) {
        this.swiad = value;
    }

    /**
     * Gets the value of the pacjent property.
     * 
     * @return
     *     possible object is
     *     {@link Swiadczeniobiorca }
     *     
     */
    public Swiadczeniobiorca getPacjent() {
        return pacjent;
    }

    /**
     * Sets the value of the pacjent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Swiadczeniobiorca }
     *     
     */
    public void setPacjent(Swiadczeniobiorca value) {
        this.pacjent = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

    /**
     * Gets the value of the idOperacji property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdOperacji() {
        return idOperacji;
    }

    /**
     * Sets the value of the idOperacji property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdOperacji(String value) {
        this.idOperacji = value;
    }

    /**
     * Gets the value of the dataCzasOperacji property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataCzasOperacji() {
        return dataCzasOperacji;
    }

    /**
     * Sets the value of the dataCzasOperacji property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataCzasOperacji(XMLGregorianCalendar value) {
        this.dataCzasOperacji = value;
    }

}
