//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.16 at 09:33:26 PM CET 
//


package pl.konczak.nzoz.ewus.client.old.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Informacja o świadczeniodawcy
 * 
 * <p>Java class for swiadczeniodawca complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="swiadczeniodawca"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id_swiad" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="id_ow"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="01"/&gt;
 *               &lt;enumeration value="02"/&gt;
 *               &lt;enumeration value="03"/&gt;
 *               &lt;enumeration value="04"/&gt;
 *               &lt;enumeration value="05"/&gt;
 *               &lt;enumeration value="06"/&gt;
 *               &lt;enumeration value="07"/&gt;
 *               &lt;enumeration value="08"/&gt;
 *               &lt;enumeration value="09"/&gt;
 *               &lt;enumeration value="10"/&gt;
 *               &lt;enumeration value="11"/&gt;
 *               &lt;enumeration value="12"/&gt;
 *               &lt;enumeration value="13"/&gt;
 *               &lt;enumeration value="14"/&gt;
 *               &lt;enumeration value="15"/&gt;
 *               &lt;enumeration value="16"/&gt;
 *               &lt;enumeration value="17"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="id_operatora" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "swiadczeniodawca", namespace = "https://ewus.nfz.gov.pl/ws/broker/ewus/status_cwu/v3", propOrder = {
    "idSwiad",
    "idOw",
    "idOperatora"
})
public class Swiadczeniodawca {

    @XmlElement(name = "id_swiad", required = true)
    protected String idSwiad;
    @XmlElement(name = "id_ow", required = true)
    protected String idOw;
    @XmlElement(name = "id_operatora", required = true)
    protected String idOperatora;

    /**
     * Gets the value of the idSwiad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdSwiad() {
        return idSwiad;
    }

    /**
     * Sets the value of the idSwiad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdSwiad(String value) {
        this.idSwiad = value;
    }

    /**
     * Gets the value of the idOw property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdOw() {
        return idOw;
    }

    /**
     * Sets the value of the idOw property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdOw(String value) {
        this.idOw = value;
    }

    /**
     * Gets the value of the idOperatora property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdOperatora() {
        return idOperatora;
    }

    /**
     * Sets the value of the idOperatora property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdOperatora(String value) {
        this.idOperatora = value;
    }

}
