//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.16 at 09:33:26 PM CET 
//


package pl.konczak.nzoz.ewus.client.old.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Informacja o świadczeniobiorcy
 * 
 * <p>Java class for swiadczeniobiorca complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="swiadczeniobiorca"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="data_waznosci_potwierdzenia" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="status_ubezp"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="ozn_rec"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                       &lt;enumeration value="DN"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="imie" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nazwisko" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "swiadczeniobiorca", namespace = "https://ewus.nfz.gov.pl/ws/broker/ewus/status_cwu/v3", propOrder = {
    "dataWaznosciPotwierdzenia",
    "statusUbezp",
    "imie",
    "nazwisko"
})
public class Swiadczeniobiorca {

    @XmlElement(name = "data_waznosci_potwierdzenia", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataWaznosciPotwierdzenia;
    @XmlElement(name = "status_ubezp", required = true)
    protected Swiadczeniobiorca.StatusUbezp statusUbezp;
    @XmlElement(required = true)
    protected String imie;
    @XmlElement(required = true)
    protected String nazwisko;

    /**
     * Gets the value of the dataWaznosciPotwierdzenia property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataWaznosciPotwierdzenia() {
        return dataWaznosciPotwierdzenia;
    }

    /**
     * Sets the value of the dataWaznosciPotwierdzenia property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataWaznosciPotwierdzenia(XMLGregorianCalendar value) {
        this.dataWaznosciPotwierdzenia = value;
    }

    /**
     * Gets the value of the statusUbezp property.
     * 
     * @return
     *     possible object is
     *     {@link Swiadczeniobiorca.StatusUbezp }
     *     
     */
    public Swiadczeniobiorca.StatusUbezp getStatusUbezp() {
        return statusUbezp;
    }

    /**
     * Sets the value of the statusUbezp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Swiadczeniobiorca.StatusUbezp }
     *     
     */
    public void setStatusUbezp(Swiadczeniobiorca.StatusUbezp value) {
        this.statusUbezp = value;
    }

    /**
     * Gets the value of the imie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImie() {
        return imie;
    }

    /**
     * Sets the value of the imie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImie(String value) {
        this.imie = value;
    }

    /**
     * Gets the value of the nazwisko property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazwisko() {
        return nazwisko;
    }

    /**
     * Sets the value of the nazwisko property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazwisko(String value) {
        this.nazwisko = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *       &lt;attribute name="ozn_rec"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *             &lt;enumeration value="DN"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class StatusUbezp {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "ozn_rec")
        protected String oznRec;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the oznRec property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOznRec() {
            return oznRec;
        }

        /**
         * Sets the value of the oznRec property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOznRec(String value) {
            this.oznRec = value;
        }

    }

}
