//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.02.16 at 09:33:26 PM CET
//
package pl.konczak.nzoz.ewus.client.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="numer_pesel" type="{https://ewus.nfz.gov.pl/ws/broker/ewus/status_cwu/v3}pesel"/&gt;
 *         &lt;element name="system_swiad" type="{https://ewus.nfz.gov.pl/ws/broker/ewus/status_cwu/v3}system"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "",
         propOrder = {
             "numerPesel",
             "systemSwiad"
         })
@XmlRootElement(name = "status_cwu_pyt",
                namespace = "https://ewus.nfz.gov.pl/ws/broker/ewus/status_cwu/v3")
public class StatusCwuPyt {

    @XmlElement(name = "numer_pesel",
                namespace = "https://ewus.nfz.gov.pl/ws/broker/ewus/status_cwu/v3",
                required = true)
    protected String numerPesel;

    @XmlElement(name = "system_swiad",
                namespace = "https://ewus.nfz.gov.pl/ws/broker/ewus/status_cwu/v3",
                required = true)
    protected System systemSwiad;

    /**
     * Gets the value of the numerPesel property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getNumerPesel() {
        return numerPesel;
    }

    /**
     * Sets the value of the numerPesel property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setNumerPesel(String value) {
        this.numerPesel = value;
    }

    /**
     * Gets the value of the systemSwiad property.
     *
     * @return possible object is {@link System }
     *
     */
    public System getSystemSwiad() {
        return systemSwiad;
    }

    /**
     * Sets the value of the systemSwiad property.
     *
     * @param value allowed object is {@link System }
     *
     */
    public void setSystemSwiad(System value) {
        this.systemSwiad = value;
    }

}
