//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.02.16 at 10:26:14 PM CET
//
package pl.konczak.nzoz.ewus.client.broker;

import pl.konczak.nzoz.ewus.client.xsd.StatusCwuPyt;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Payload complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Payload"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="textload" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;any/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="streamload" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="stream" type="{http://www.w3.org/2005/05/xmlmime}base64Binary"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Payload",
         namespace = "http://xml.kamsoft.pl/ws/broker",
         propOrder = {
             "textload",
             "streamload"
         })
@XmlSeeAlso(StatusCwuPyt.class)
public class Payload {

    protected Payload.Textload textload;

    protected Payload.Streamload streamload;

    /**
     * Gets the value of the textload property.
     *
     * @return possible object is {@link Payload.Textload }
     *
     */
    public Payload.Textload getTextload() {
        return textload;
    }

    /**
     * Sets the value of the textload property.
     *
     * @param value allowed object is {@link Payload.Textload }
     *
     */
    public void setTextload(Payload.Textload value) {
        this.textload = value;
    }

    /**
     * Gets the value of the streamload property.
     *
     * @return possible object is {@link Payload.Streamload }
     *
     */
    public Payload.Streamload getStreamload() {
        return streamload;
    }

    /**
     * Sets the value of the streamload property.
     *
     * @param value allowed object is {@link Payload.Streamload }
     *
     */
    public void setStreamload(Payload.Streamload value) {
        this.streamload = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="stream" type="{http://www.w3.org/2005/05/xmlmime}base64Binary"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "",
             propOrder = {
                 "stream"
             })
    public static class Streamload {

        @XmlElement(namespace = "http://xml.kamsoft.pl/ws/broker",
                    required = true)
        protected Base64Binary stream;

        @XmlAttribute(name = "name",
                      required = true)
        protected String name;

        /**
         * Gets the value of the stream property.
         *
         * @return possible object is {@link Base64Binary }
         *
         */
        public Base64Binary getStream() {
            return stream;
        }

        /**
         * Sets the value of the stream property.
         *
         * @param value allowed object is {@link Base64Binary }
         *
         */
        public void setStream(Base64Binary value) {
            this.stream = value;
        }

        /**
         * Gets the value of the name property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setName(String value) {
            this.name = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;any/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "",
             propOrder = {
                 "any"
             })
    public static class Textload {

        @XmlAnyElement(lax = true)
        protected Object any;

        /**
         * Gets the value of the any property.
         *
         * @return possible object is {@link Object }
         *
         */
        public Object getAny() {
            return any;
        }

        /**
         * Sets the value of the any property.
         *
         * @param value allowed object is {@link Object }
         *
         */
        public void setAny(Object value) {
            this.any = value;
        }

    }

}
