//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.16 at 10:26:14 PM CET 
//


package pl.konczak.nzoz.ewus.client.old.broker;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Mozliwe sa parametry o nastepujacych nazwach:
 *  1) domain - domena logowania - przyjmuje dwucyfrowy kod OW
 *  2) idntSwd - kod swiadczeniodawcy
 *  3) login - login operatora
 *  4) type - typ operatora (mozliwe wartosci: SWD, LEK)
 * 
 * Powyzsze parametry tworza nastepujace warianty umozliwiajace autentykacje:
 *  1) domain, login - operator w systemie KS-Katowice
 *  2) domain, type=LEK, login -  operartor typu lekarz w systemie KS-Gliwice
 *  3) domain, idntSwd, login, type=SWD - operator typu swiadczeniodawca w systemie KS-Gliwice
 * 
 * <p>Java class for loginParams complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="loginParams"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="item" type="{http://xml.kamsoft.pl/ws/kaas/login_types}loginParam" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "loginParams", namespace = "http://xml.kamsoft.pl/ws/kaas/login_types", propOrder = {
    "item"
})
public class LoginParams {

    @XmlElement(required = true)
    protected List<LoginParam> item;

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LoginParam }
     * 
     * 
     */
    public List<LoginParam> getItem() {
        if (item == null) {
            item = new ArrayList<LoginParam>();
        }
        return this.item;
    }

}
