//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.16 at 10:26:14 PM CET 
//


package pl.konczak.nzoz.ewus.client.old.broker;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.konczak.nzoz.ewus.client.broker package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Login_QNAME = new QName("http://xml.kamsoft.pl/ws/kaas/login_types", "login");
    private final static QName _LoginReturn_QNAME = new QName("http://xml.kamsoft.pl/ws/kaas/login_types", "loginReturn");
    private final static QName _Logout_QNAME = new QName("http://xml.kamsoft.pl/ws/kaas/login_types", "logout");
    private final static QName _LogoutReturn_QNAME = new QName("http://xml.kamsoft.pl/ws/kaas/login_types", "logoutReturn");
    private final static QName _ChangePassword_QNAME = new QName("http://xml.kamsoft.pl/ws/kaas/login_types", "changePassword");
    private final static QName _ChangePasswordLog_QNAME = new QName("http://xml.kamsoft.pl/ws/kaas/login_types", "changePasswordLog");
    private final static QName _ChangePasswordReturn_QNAME = new QName("http://xml.kamsoft.pl/ws/kaas/login_types", "changePasswordReturn");
    private final static QName _ExecuteService_QNAME = new QName("http://xml.kamsoft.pl/ws/broker", "executeService");
    private final static QName _ExecuteServiceReturn_QNAME = new QName("http://xml.kamsoft.pl/ws/broker", "executeServiceReturn");
    private final static QName _SessionError_QNAME = new QName("http://xml.kamsoft.pl/ws/common", "sessionError");
    private final static QName _PassExpiredError_QNAME = new QName("http://xml.kamsoft.pl/ws/common", "passExpiredError");
    private final static QName _AuthTokenError_QNAME = new QName("http://xml.kamsoft.pl/ws/common", "authTokenError");
    private final static QName _AuthenticationError_QNAME = new QName("http://xml.kamsoft.pl/ws/common", "authenticationError");
    private final static QName _AuthorizationError_QNAME = new QName("http://xml.kamsoft.pl/ws/common", "authorizationError");
    private final static QName _InputError_QNAME = new QName("http://xml.kamsoft.pl/ws/common", "inputError");
    private final static QName _ServiceError_QNAME = new QName("http://xml.kamsoft.pl/ws/common", "serviceError");
    private final static QName _ServerError_QNAME = new QName("http://xml.kamsoft.pl/ws/common", "serverError");
    private final static QName _Location_QNAME = new QName("http://xml.kamsoft.pl/ws/common", "location");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.konczak.nzoz.ewus.client.broker
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Payload }
     * 
     */
    public Payload createPayload() {
        return new Payload();
    }

    /**
     * Create an instance of {@link ParamValue }
     * 
     */
    public ParamValue createParamValue() {
        return new ParamValue();
    }

    /**
     * Create an instance of {@link LoginRequest }
     * 
     */
    public LoginRequest createLoginRequest() {
        return new LoginRequest();
    }

    /**
     * Create an instance of {@link ChangePasswordParams }
     * 
     */
    public ChangePasswordParams createChangePasswordParams() {
        return new ChangePasswordParams();
    }

    /**
     * Create an instance of {@link LoginParam }
     * 
     */
    public LoginParam createLoginParam() {
        return new LoginParam();
    }

    /**
     * Create an instance of {@link LoginParams }
     * 
     */
    public LoginParams createLoginParams() {
        return new LoginParams();
    }

    /**
     * Create an instance of {@link ServiceRequest }
     * 
     */
    public ServiceRequest createServiceRequest() {
        return new ServiceRequest();
    }

    /**
     * Create an instance of {@link ServiceResponse }
     * 
     */
    public ServiceResponse createServiceResponse() {
        return new ServiceResponse();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link ArrayOfParam }
     * 
     */
    public ArrayOfParam createArrayOfParam() {
        return new ArrayOfParam();
    }

    /**
     * Create an instance of {@link Base64Binary }
     * 
     */
    public Base64Binary createBase64Binary() {
        return new Base64Binary();
    }

    /**
     * Create an instance of {@link HexBinary }
     * 
     */
    public HexBinary createHexBinary() {
        return new HexBinary();
    }

    /**
     * Create an instance of {@link SessionException }
     * 
     */
    public SessionException createSessionException() {
        return new SessionException();
    }

    /**
     * Create an instance of {@link PassExpiredException }
     * 
     */
    public PassExpiredException createPassExpiredException() {
        return new PassExpiredException();
    }

    /**
     * Create an instance of {@link AuthTokenException }
     * 
     */
    public AuthTokenException createAuthTokenException() {
        return new AuthTokenException();
    }

    /**
     * Create an instance of {@link AuthenticationException }
     * 
     */
    public AuthenticationException createAuthenticationException() {
        return new AuthenticationException();
    }

    /**
     * Create an instance of {@link AuthorizationException }
     * 
     */
    public AuthorizationException createAuthorizationException() {
        return new AuthorizationException();
    }

    /**
     * Create an instance of {@link InputException }
     * 
     */
    public InputException createInputException() {
        return new InputException();
    }

    /**
     * Create an instance of {@link ServiceException }
     * 
     */
    public ServiceException createServiceException() {
        return new ServiceException();
    }

    /**
     * Create an instance of {@link ServerException }
     * 
     */
    public ServerException createServerException() {
        return new ServerException();
    }

    /**
     * Create an instance of {@link ServiceLocation }
     * 
     */
    public ServiceLocation createServiceLocation() {
        return new ServiceLocation();
    }

    /**
     * Create an instance of {@link AuthToken }
     * 
     */
    public AuthToken createAuthToken() {
        return new AuthToken();
    }

    /**
     * Create an instance of {@link Session }
     * 
     */
    public Session createSession() {
        return new Session();
    }

    /**
     * Create an instance of {@link ArrayOfMessage }
     * 
     */
    public ArrayOfMessage createArrayOfMessage() {
        return new ArrayOfMessage();
    }

    /**
     * Create an instance of {@link BaseException }
     * 
     */
    public BaseException createBaseException() {
        return new BaseException();
    }

    /**
     * Create an instance of {@link Payload.Textload }
     * 
     */
    public Payload.Textload createPayloadTextload() {
        return new Payload.Textload();
    }

    /**
     * Create an instance of {@link Payload.Streamload }
     * 
     */
    public Payload.Streamload createPayloadStreamload() {
        return new Payload.Streamload();
    }

    /**
     * Create an instance of {@link ParamValue.AnyValue }
     * 
     */
    public ParamValue.AnyValue createParamValueAnyValue() {
        return new ParamValue.AnyValue();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoginRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.kamsoft.pl/ws/kaas/login_types", name = "login")
    public JAXBElement<LoginRequest> createLogin(LoginRequest value) {
        return new JAXBElement<LoginRequest>(_Login_QNAME, LoginRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.kamsoft.pl/ws/kaas/login_types", name = "loginReturn")
    public JAXBElement<String> createLoginReturn(String value) {
        return new JAXBElement<String>(_LoginReturn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.kamsoft.pl/ws/kaas/login_types", name = "logout")
    public JAXBElement<String> createLogout(String value) {
        return new JAXBElement<String>(_Logout_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.kamsoft.pl/ws/kaas/login_types", name = "logoutReturn")
    public JAXBElement<String> createLogoutReturn(String value) {
        return new JAXBElement<String>(_LogoutReturn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChangePasswordParams }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.kamsoft.pl/ws/kaas/login_types", name = "changePassword")
    public JAXBElement<ChangePasswordParams> createChangePassword(ChangePasswordParams value) {
        return new JAXBElement<ChangePasswordParams>(_ChangePassword_QNAME, ChangePasswordParams.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChangePasswordParams }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.kamsoft.pl/ws/kaas/login_types", name = "changePasswordLog")
    public JAXBElement<ChangePasswordParams> createChangePasswordLog(ChangePasswordParams value) {
        return new JAXBElement<ChangePasswordParams>(_ChangePasswordLog_QNAME, ChangePasswordParams.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.kamsoft.pl/ws/kaas/login_types", name = "changePasswordReturn")
    public JAXBElement<String> createChangePasswordReturn(String value) {
        return new JAXBElement<String>(_ChangePasswordReturn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.kamsoft.pl/ws/broker", name = "executeService")
    public JAXBElement<ServiceRequest> createExecuteService(ServiceRequest value) {
        return new JAXBElement<ServiceRequest>(_ExecuteService_QNAME, ServiceRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.kamsoft.pl/ws/broker", name = "executeServiceReturn")
    public JAXBElement<ServiceResponse> createExecuteServiceReturn(ServiceResponse value) {
        return new JAXBElement<ServiceResponse>(_ExecuteServiceReturn_QNAME, ServiceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SessionException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.kamsoft.pl/ws/common", name = "sessionError")
    public JAXBElement<SessionException> createSessionError(SessionException value) {
        return new JAXBElement<SessionException>(_SessionError_QNAME, SessionException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PassExpiredException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.kamsoft.pl/ws/common", name = "passExpiredError")
    public JAXBElement<PassExpiredException> createPassExpiredError(PassExpiredException value) {
        return new JAXBElement<PassExpiredException>(_PassExpiredError_QNAME, PassExpiredException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthTokenException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.kamsoft.pl/ws/common", name = "authTokenError")
    public JAXBElement<AuthTokenException> createAuthTokenError(AuthTokenException value) {
        return new JAXBElement<AuthTokenException>(_AuthTokenError_QNAME, AuthTokenException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthenticationException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.kamsoft.pl/ws/common", name = "authenticationError")
    public JAXBElement<AuthenticationException> createAuthenticationError(AuthenticationException value) {
        return new JAXBElement<AuthenticationException>(_AuthenticationError_QNAME, AuthenticationException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorizationException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.kamsoft.pl/ws/common", name = "authorizationError")
    public JAXBElement<AuthorizationException> createAuthorizationError(AuthorizationException value) {
        return new JAXBElement<AuthorizationException>(_AuthorizationError_QNAME, AuthorizationException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InputException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.kamsoft.pl/ws/common", name = "inputError")
    public JAXBElement<InputException> createInputError(InputException value) {
        return new JAXBElement<InputException>(_InputError_QNAME, InputException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.kamsoft.pl/ws/common", name = "serviceError")
    public JAXBElement<ServiceException> createServiceError(ServiceException value) {
        return new JAXBElement<ServiceException>(_ServiceError_QNAME, ServiceException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServerException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.kamsoft.pl/ws/common", name = "serverError")
    public JAXBElement<ServerException> createServerError(ServerException value) {
        return new JAXBElement<ServerException>(_ServerError_QNAME, ServerException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceLocation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.kamsoft.pl/ws/common", name = "location")
    public JAXBElement<ServiceLocation> createLocation(ServiceLocation value) {
        return new JAXBElement<ServiceLocation>(_Location_QNAME, ServiceLocation.class, null, value);
    }

}
