//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.16 at 10:26:14 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xml.kamsoft.pl/ws/common", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pl.konczak.nzoz.ewus.client.old.broker;
